name: Build

on:
  push:
    paths:
      - 'apps/**'
      - 'test/unit/**'
      - 'web-test-runner.config.mjs'
      - '.github/workflows/main.yaml'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm install
      - run: npm run lint

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm install
      - run: npm test
